import json
import re
import torch


def create_qwen_prompt(example, tokenizer):
    """
    Create a Qwen-compatible tool-calling prompt.

    Parameters
    ----------
    example : dict
        Dataset example containing:
        - query
        - tools

    tokenizer
        Qwen tokenizer with chat template support.

    Returns
    -------
    str
        Formatted prompt.
    """

    query = example["query"]
    tools = json.loads(example["tools"])

    messages = [
        {
            "role": "user",
            "content": query
        }
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tools=tools,
        tokenize=False,
        add_generation_prompt=True
    )

    return formatted_prompt


def parse_tool_calls(raw_response):
    """
    Extract tool calls from the raw model response.

    Parameters
    ----------
    raw_response : str
        Raw text generated by the model.

    Returns
    -------
    list
        List of parsed tool call dictionaries.
    """

    tool_call_blocks = re.findall(
        r"<tool_call>\s*(.*?)\s*</tool_call>",
        raw_response,
        re.DOTALL
    )

    parsed_calls = []

    for block in tool_call_blocks:

        try:
            tool_call = json.loads(block)
            parsed_calls.append(tool_call)

        except json.JSONDecodeError:
            continue

    return parsed_calls


def predict_tool_calls(
    example,
    model,
    tokenizer,
    max_new_tokens=256
):
    """
    Generate tool calls for a single example.

    Parameters
    ----------
    example : dict
        Dataset example.

    model
        Loaded language model.

    tokenizer
        Model tokenizer.

    max_new_tokens : int
        Maximum number of tokens to generate.

    Returns
    -------
    predicted_calls : list
        Parsed predicted tool calls.

    raw_response : str
        Raw generated model response.
    """

    # ------------------------------------------------------------
    # Create prompt
    # ------------------------------------------------------------

    formatted_prompt = create_qwen_prompt(
        example,
        tokenizer
    )

    # ------------------------------------------------------------
    # Tokenize
    # ------------------------------------------------------------

    model_inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt"
    )

    model_inputs = {
        key: value.to(model.device)
        for key, value in model_inputs.items()
    }

    # ------------------------------------------------------------
    # Generate
    # ------------------------------------------------------------

    with torch.inference_mode():

        output_ids = model.generate(
            **model_inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    # ------------------------------------------------------------
    # Extract only newly generated tokens
    # ------------------------------------------------------------

    input_length = model_inputs["input_ids"].shape[1]

    generated_ids = output_ids[:, input_length:]

    # ------------------------------------------------------------
    # Decode
    # ------------------------------------------------------------

    raw_response = tokenizer.decode(
        generated_ids[0],
        skip_special_tokens=False
    )

    # ------------------------------------------------------------
    # Parse tool calls
    # ------------------------------------------------------------

    predicted_calls = parse_tool_calls(raw_response)

    return predicted_calls, raw_response